//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 25.11.2014 10:03:13
namespace NoiseManagement.DataContext
{
    
    /// <summary>
    /// There are no comments for DomainModelContext in the schema.
    /// </summary>
    public partial class DomainModelContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DomainModelContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DomainModelContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("OpenResKit.DomainModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("NoiseManagement.DataContext", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("NoiseManagement.DataContext", global::System.StringComparison.Ordinal))
            {
                return string.Concat("OpenResKit.DomainModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for NoiseMeasurements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseMeasurement> NoiseMeasurements
        {
            get
            {
                if ((this._NoiseMeasurements == null))
                {
                    this._NoiseMeasurements = base.CreateQuery<NoiseMeasurement>("NoiseMeasurements");
                }
                return this._NoiseMeasurements;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseMeasurement> _NoiseMeasurements;
        /// <summary>
        /// There are no comments for MeasuringDevices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MeasuringDevice> MeasuringDevices
        {
            get
            {
                if ((this._MeasuringDevices == null))
                {
                    this._MeasuringDevices = base.CreateQuery<MeasuringDevice>("MeasuringDevices");
                }
                return this._MeasuringDevices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MeasuringDevice> _MeasuringDevices;
        /// <summary>
        /// There are no comments for LegalBasis in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<LegalBasis> LegalBasis
        {
            get
            {
                if ((this._LegalBasis == null))
                {
                    this._LegalBasis = base.CreateQuery<LegalBasis>("LegalBasis");
                }
                return this._LegalBasis;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<LegalBasis> _LegalBasis;
        /// <summary>
        /// There are no comments for NoiseEmployees in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseEmployee> NoiseEmployees
        {
            get
            {
                if ((this._NoiseEmployees == null))
                {
                    this._NoiseEmployees = base.CreateQuery<NoiseEmployee>("NoiseEmployees");
                }
                return this._NoiseEmployees;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseEmployee> _NoiseEmployees;
        /// <summary>
        /// There are no comments for MeasuringPoints in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MeasuringPoint> MeasuringPoints
        {
            get
            {
                if ((this._MeasuringPoints == null))
                {
                    this._MeasuringPoints = base.CreateQuery<MeasuringPoint>("MeasuringPoints");
                }
                return this._MeasuringPoints;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MeasuringPoint> _MeasuringPoints;
        /// <summary>
        /// There are no comments for DescriptivePositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DescriptivePosition> DescriptivePositions
        {
            get
            {
                if ((this._DescriptivePositions == null))
                {
                    this._DescriptivePositions = base.CreateQuery<DescriptivePosition>("DescriptivePositions");
                }
                return this._DescriptivePositions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DescriptivePosition> _DescriptivePositions;
        /// <summary>
        /// There are no comments for NoiseMapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseMapPosition> NoiseMapPositions
        {
            get
            {
                if ((this._NoiseMapPositions == null))
                {
                    this._NoiseMapPositions = base.CreateQuery<NoiseMapPosition>("NoiseMapPositions");
                }
                return this._NoiseMapPositions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseMapPosition> _NoiseMapPositions;
        /// <summary>
        /// There are no comments for NoiseMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<NoiseMap> NoiseMaps
        {
            get
            {
                if ((this._NoiseMaps == null))
                {
                    this._NoiseMaps = base.CreateQuery<NoiseMap>("NoiseMaps");
                }
                return this._NoiseMaps;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<NoiseMap> _NoiseMaps;
        /// <summary>
        /// There are no comments for Files in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<File> Files
        {
            get
            {
                if ((this._Files == null))
                {
                    this._Files = base.CreateQuery<File>("Files");
                }
                return this._Files;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<File> _Files;
        /// <summary>
        /// There are no comments for GeoPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GeoPosition> GeoPositions
        {
            get
            {
                if ((this._GeoPositions == null))
                {
                    this._GeoPositions = base.CreateQuery<GeoPosition>("GeoPositions");
                }
                return this._GeoPositions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GeoPosition> _GeoPositions;
        /// <summary>
        /// There are no comments for Attachments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Attachment> Attachments
        {
            get
            {
                if ((this._Attachments == null))
                {
                    this._Attachments = base.CreateQuery<Attachment>("Attachments");
                }
                return this._Attachments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Attachment> _Attachments;
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Comment> Comments
        {
            get
            {
                if ((this._Comments == null))
                {
                    this._Comments = base.CreateQuery<Comment>("Comments");
                }
                return this._Comments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Comment> _Comments;
        /// <summary>
        /// There are no comments for LogEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<LogEntry> LogEntries
        {
            get
            {
                if ((this._LogEntries == null))
                {
                    this._LogEntries = base.CreateQuery<LogEntry>("LogEntries");
                }
                return this._LogEntries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<LogEntry> _LogEntries;
        /// <summary>
        /// There are no comments for NoiseMeasurements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseMeasurements(NoiseMeasurement noiseMeasurement)
        {
            base.AddObject("NoiseMeasurements", noiseMeasurement);
        }
        /// <summary>
        /// There are no comments for MeasuringDevices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeasuringDevices(MeasuringDevice measuringDevice)
        {
            base.AddObject("MeasuringDevices", measuringDevice);
        }
        /// <summary>
        /// There are no comments for LegalBasis in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLegalBasis(LegalBasis legalBasis)
        {
            base.AddObject("LegalBasis", legalBasis);
        }
        /// <summary>
        /// There are no comments for NoiseEmployees in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseEmployees(NoiseEmployee noiseEmployee)
        {
            base.AddObject("NoiseEmployees", noiseEmployee);
        }
        /// <summary>
        /// There are no comments for MeasuringPoints in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeasuringPoints(MeasuringPoint measuringPoint)
        {
            base.AddObject("MeasuringPoints", measuringPoint);
        }
        /// <summary>
        /// There are no comments for DescriptivePositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDescriptivePositions(DescriptivePosition descriptivePosition)
        {
            base.AddObject("DescriptivePositions", descriptivePosition);
        }
        /// <summary>
        /// There are no comments for NoiseMapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseMapPositions(NoiseMapPosition noiseMapPosition)
        {
            base.AddObject("NoiseMapPositions", noiseMapPosition);
        }
        /// <summary>
        /// There are no comments for NoiseMaps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToNoiseMaps(NoiseMap noiseMap)
        {
            base.AddObject("NoiseMaps", noiseMap);
        }
        /// <summary>
        /// There are no comments for Files in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFiles(File file)
        {
            base.AddObject("Files", file);
        }
        /// <summary>
        /// There are no comments for GeoPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGeoPositions(GeoPosition geoPosition)
        {
            base.AddObject("GeoPositions", geoPosition);
        }
        /// <summary>
        /// There are no comments for Attachments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAttachments(Attachment attachment)
        {
            base.AddObject("Attachments", attachment);
        }
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToComments(Comment comment)
        {
            base.AddObject("Comments", comment);
        }
        /// <summary>
        /// There are no comments for LogEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLogEntries(LogEntry logEntry)
        {
            base.AddObject("LogEntries", logEntry);
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.NoiseMeasurement in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseMeasurements")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseMeasurement : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new NoiseMeasurement object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="measurementDate">Initial value of MeasurementDate.</param>
        /// <param name="minValue">Initial value of MinValue.</param>
        /// <param name="maxValue">Initial value of MaxValue.</param>
        /// <param name="averageValue">Initial value of AverageValue.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseMeasurement CreateNoiseMeasurement(int ID, global::System.DateTime measurementDate, float minValue, float maxValue, float averageValue)
        {
            NoiseMeasurement noiseMeasurement = new NoiseMeasurement();
            noiseMeasurement.Id = ID;
            noiseMeasurement.MeasurementDate = measurementDate;
            noiseMeasurement.MinValue = minValue;
            noiseMeasurement.MaxValue = maxValue;
            noiseMeasurement.AverageValue = averageValue;
            return noiseMeasurement;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MeasurementDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime MeasurementDate
        {
            get
            {
                return this._MeasurementDate;
            }
            set
            {
                this.OnMeasurementDateChanging(value);
                this._MeasurementDate = value;
                this.OnMeasurementDateChanged();
                this.OnPropertyChanged("MeasurementDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _MeasurementDate;
        partial void OnMeasurementDateChanging(global::System.DateTime value);
        partial void OnMeasurementDateChanged();
        /// <summary>
        /// There are no comments for Property MinValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float MinValue
        {
            get
            {
                return this._MinValue;
            }
            set
            {
                this.OnMinValueChanging(value);
                this._MinValue = value;
                this.OnMinValueChanged();
                this.OnPropertyChanged("MinValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _MinValue;
        partial void OnMinValueChanging(float value);
        partial void OnMinValueChanged();
        /// <summary>
        /// There are no comments for Property MaxValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float MaxValue
        {
            get
            {
                return this._MaxValue;
            }
            set
            {
                this.OnMaxValueChanging(value);
                this._MaxValue = value;
                this.OnMaxValueChanged();
                this.OnPropertyChanged("MaxValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _MaxValue;
        partial void OnMaxValueChanging(float value);
        partial void OnMaxValueChanged();
        /// <summary>
        /// There are no comments for Property AverageValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float AverageValue
        {
            get
            {
                return this._AverageValue;
            }
            set
            {
                this.OnAverageValueChanging(value);
                this._AverageValue = value;
                this.OnAverageValueChanged();
                this.OnPropertyChanged("AverageValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _AverageValue;
        partial void OnAverageValueChanging(float value);
        partial void OnAverageValueChanged();
        /// <summary>
        /// There are no comments for MeasuringDevice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MeasuringDevice MeasuringDevice
        {
            get
            {
                return this._MeasuringDevice;
            }
            set
            {
                this._MeasuringDevice = value;
                this.OnPropertyChanged("MeasuringDevice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MeasuringDevice _MeasuringDevice;
        /// <summary>
        /// There are no comments for LegalBasis in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public LegalBasis LegalBasis
        {
            get
            {
                return this._LegalBasis;
            }
            set
            {
                this._LegalBasis = value;
                this.OnPropertyChanged("LegalBasis");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private LegalBasis _LegalBasis;
        /// <summary>
        /// There are no comments for NoiseEmployee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NoiseEmployee NoiseEmployee
        {
            get
            {
                return this._NoiseEmployee;
            }
            set
            {
                this._NoiseEmployee = value;
                this.OnPropertyChanged("NoiseEmployee");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private NoiseEmployee _NoiseEmployee;
        /// <summary>
        /// There are no comments for MeasuringPoint in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MeasuringPoint MeasuringPoint
        {
            get
            {
                return this._MeasuringPoint;
            }
            set
            {
                this._MeasuringPoint = value;
                this.OnPropertyChanged("MeasuringPoint");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MeasuringPoint _MeasuringPoint;
        /// <summary>
        /// There are no comments for Attachments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Attachment> Attachments
        {
            get
            {
                return this._Attachments;
            }
            set
            {
                this._Attachments = value;
                this.OnPropertyChanged("Attachments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Attachment> _Attachments = new global::System.Data.Services.Client.DataServiceCollection<Attachment>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Comments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Comment> Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this._Comments = value;
                this.OnPropertyChanged("Comments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Comment> _Comments = new global::System.Data.Services.Client.DataServiceCollection<Comment>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MeasuringDevice in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeasuringDevices")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MeasuringDevice : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MeasuringDevice object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeasuringDevice CreateMeasuringDevice(int ID)
        {
            MeasuringDevice measuringDevice = new MeasuringDevice();
            measuringDevice.Id = ID;
            return measuringDevice;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.LegalBasis in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("LegalBasis")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class LegalBasis : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LegalBasis object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="date">Initial value of Date.</param>
        /// <param name="greenValue">Initial value of GreenValue.</param>
        /// <param name="yellowValue">Initial value of YellowValue.</param>
        /// <param name="redValue">Initial value of RedValue.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static LegalBasis CreateLegalBasis(int ID, global::System.DateTime date, float greenValue, float yellowValue, float redValue)
        {
            LegalBasis legalBasis = new LegalBasis();
            legalBasis.Id = ID;
            legalBasis.Date = date;
            legalBasis.GreenValue = greenValue;
            legalBasis.YellowValue = yellowValue;
            legalBasis.RedValue = redValue;
            return legalBasis;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property GreenValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float GreenValue
        {
            get
            {
                return this._GreenValue;
            }
            set
            {
                this.OnGreenValueChanging(value);
                this._GreenValue = value;
                this.OnGreenValueChanged();
                this.OnPropertyChanged("GreenValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _GreenValue;
        partial void OnGreenValueChanging(float value);
        partial void OnGreenValueChanged();
        /// <summary>
        /// There are no comments for Property YellowValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float YellowValue
        {
            get
            {
                return this._YellowValue;
            }
            set
            {
                this.OnYellowValueChanging(value);
                this._YellowValue = value;
                this.OnYellowValueChanged();
                this.OnPropertyChanged("YellowValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _YellowValue;
        partial void OnYellowValueChanging(float value);
        partial void OnYellowValueChanged();
        /// <summary>
        /// There are no comments for Property RedValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float RedValue
        {
            get
            {
                return this._RedValue;
            }
            set
            {
                this.OnRedValueChanging(value);
                this._RedValue = value;
                this.OnRedValueChanged();
                this.OnPropertyChanged("RedValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _RedValue;
        partial void OnRedValueChanging(float value);
        partial void OnRedValueChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.NoiseEmployee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseEmployees")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseEmployee : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new NoiseEmployee object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="role">Initial value of Role.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseEmployee CreateNoiseEmployee(int ID, int role)
        {
            NoiseEmployee noiseEmployee = new NoiseEmployee();
            noiseEmployee.Id = ID;
            noiseEmployee.Role = role;
            return noiseEmployee;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Role in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Role
        {
            get
            {
                return this._Role;
            }
            set
            {
                this.OnRoleChanging(value);
                this._Role = value;
                this.OnRoleChanged();
                this.OnPropertyChanged("Role");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Role;
        partial void OnRoleChanging(int value);
        partial void OnRoleChanged();
        /// <summary>
        /// There are no comments for Property Department in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Department
        {
            get
            {
                return this._Department;
            }
            set
            {
                this.OnDepartmentChanging(value);
                this._Department = value;
                this.OnDepartmentChanged();
                this.OnPropertyChanged("Department");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Department;
        partial void OnDepartmentChanging(string value);
        partial void OnDepartmentChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MeasuringPoint in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeasuringPoints")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MeasuringPoint : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MeasuringPoint object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeasuringPoint CreateMeasuringPoint(int ID)
        {
            MeasuringPoint measuringPoint = new MeasuringPoint();
            measuringPoint.Id = ID;
            return measuringPoint;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Barcode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Barcode
        {
            get
            {
                return this._Barcode;
            }
            set
            {
                this.OnBarcodeChanging(value);
                this._Barcode = value;
                this.OnBarcodeChanged();
                this.OnPropertyChanged("Barcode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Barcode;
        partial void OnBarcodeChanging(string value);
        partial void OnBarcodeChanged();
        /// <summary>
        /// There are no comments for DescriptivePosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DescriptivePosition DescriptivePosition
        {
            get
            {
                return this._DescriptivePosition;
            }
            set
            {
                this._DescriptivePosition = value;
                this.OnPropertyChanged("DescriptivePosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DescriptivePosition _DescriptivePosition;
        /// <summary>
        /// There are no comments for NoiseMapPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NoiseMapPosition NoiseMapPosition
        {
            get
            {
                return this._NoiseMapPosition;
            }
            set
            {
                this._NoiseMapPosition = value;
                this.OnPropertyChanged("NoiseMapPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private NoiseMapPosition _NoiseMapPosition;
        /// <summary>
        /// There are no comments for GeoPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public GeoPosition GeoPosition
        {
            get
            {
                return this._GeoPosition;
            }
            set
            {
                this._GeoPosition = value;
                this.OnPropertyChanged("GeoPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private GeoPosition _GeoPosition;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.DescriptivePosition in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DescriptivePositions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DescriptivePosition : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DescriptivePosition object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DescriptivePosition CreateDescriptivePosition(int ID)
        {
            DescriptivePosition descriptivePosition = new DescriptivePosition();
            descriptivePosition.Id = ID;
            return descriptivePosition;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Site in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Site
        {
            get
            {
                return this._Site;
            }
            set
            {
                this.OnSiteChanging(value);
                this._Site = value;
                this.OnSiteChanged();
                this.OnPropertyChanged("Site");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Site;
        partial void OnSiteChanging(string value);
        partial void OnSiteChanged();
        /// <summary>
        /// There are no comments for Property Building in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Building
        {
            get
            {
                return this._Building;
            }
            set
            {
                this.OnBuildingChanging(value);
                this._Building = value;
                this.OnBuildingChanged();
                this.OnPropertyChanged("Building");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Building;
        partial void OnBuildingChanging(string value);
        partial void OnBuildingChanged();
        /// <summary>
        /// There are no comments for Property Level in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this._Level = value;
                this.OnLevelChanged();
                this.OnPropertyChanged("Level");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Level;
        partial void OnLevelChanging(string value);
        partial void OnLevelChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.NoiseMapPosition in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseMapPositions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseMapPosition : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new NoiseMapPosition object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="xPosition">Initial value of XPosition.</param>
        /// <param name="yPosition">Initial value of YPosition.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseMapPosition CreateNoiseMapPosition(int ID, int xPosition, int yPosition)
        {
            NoiseMapPosition noiseMapPosition = new NoiseMapPosition();
            noiseMapPosition.Id = ID;
            noiseMapPosition.XPosition = xPosition;
            noiseMapPosition.YPosition = yPosition;
            return noiseMapPosition;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property XPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int XPosition
        {
            get
            {
                return this._XPosition;
            }
            set
            {
                this.OnXPositionChanging(value);
                this._XPosition = value;
                this.OnXPositionChanged();
                this.OnPropertyChanged("XPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _XPosition;
        partial void OnXPositionChanging(int value);
        partial void OnXPositionChanged();
        /// <summary>
        /// There are no comments for Property YPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int YPosition
        {
            get
            {
                return this._YPosition;
            }
            set
            {
                this.OnYPositionChanging(value);
                this._YPosition = value;
                this.OnYPositionChanged();
                this.OnPropertyChanged("YPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _YPosition;
        partial void OnYPositionChanging(int value);
        partial void OnYPositionChanged();
        /// <summary>
        /// There are no comments for NoiseMap in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NoiseMap NoiseMap
        {
            get
            {
                return this._NoiseMap;
            }
            set
            {
                this._NoiseMap = value;
                this.OnPropertyChanged("NoiseMap");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private NoiseMap _NoiseMap;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.NoiseMap in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("NoiseMaps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class NoiseMap : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new NoiseMap object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static NoiseMap CreateNoiseMap(int ID)
        {
            NoiseMap noiseMap = new NoiseMap();
            noiseMap.Id = ID;
            return noiseMap;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for File in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public File File
        {
            get
            {
                return this._File;
            }
            set
            {
                this._File = value;
                this.OnPropertyChanged("File");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private File _File;
        /// <summary>
        /// There are no comments for DescriptivePosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DescriptivePosition DescriptivePosition
        {
            get
            {
                return this._DescriptivePosition;
            }
            set
            {
                this._DescriptivePosition = value;
                this.OnPropertyChanged("DescriptivePosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DescriptivePosition _DescriptivePosition;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.File in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Files")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class File : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new File object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static File CreateFile(int ID)
        {
            File file = new File();
            file.Id = ID;
            return file;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property BinarySource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] BinarySource
        {
            get
            {
                if ((this._BinarySource != null))
                {
                    return ((byte[])(this._BinarySource.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnBinarySourceChanging(value);
                this._BinarySource = value;
                this.OnBinarySourceChanged();
                this.OnPropertyChanged("BinarySource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _BinarySource;
        partial void OnBinarySourceChanging(byte[] value);
        partial void OnBinarySourceChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.GeoPosition in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("GeoPositions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class GeoPosition : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new GeoPosition object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="latitude">Initial value of Latitude.</param>
        /// <param name="longitude">Initial value of Longitude.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GeoPosition CreateGeoPosition(int ID, double latitude, double longitude)
        {
            GeoPosition geoPosition = new GeoPosition();
            geoPosition.Id = ID;
            geoPosition.Latitude = latitude;
            geoPosition.Longitude = longitude;
            return geoPosition;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Latitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Latitude
        {
            get
            {
                return this._Latitude;
            }
            set
            {
                this.OnLatitudeChanging(value);
                this._Latitude = value;
                this.OnLatitudeChanged();
                this.OnPropertyChanged("Latitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Latitude;
        partial void OnLatitudeChanging(double value);
        partial void OnLatitudeChanged();
        /// <summary>
        /// There are no comments for Property Longitude in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Longitude
        {
            get
            {
                return this._Longitude;
            }
            set
            {
                this.OnLongitudeChanging(value);
                this._Longitude = value;
                this.OnLongitudeChanged();
                this.OnPropertyChanged("Longitude");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Longitude;
        partial void OnLongitudeChanging(double value);
        partial void OnLongitudeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Attachment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Attachments")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Attachment : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Attachment object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Attachment CreateAttachment(int ID)
        {
            Attachment attachment = new Attachment();
            attachment.Id = ID;
            return attachment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FileName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this._FileName = value;
                this.OnFileNameChanged();
                this.OnPropertyChanged("FileName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
        /// <summary>
        /// There are no comments for File in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public File File
        {
            get
            {
                return this._File;
            }
            set
            {
                this._File = value;
                this.OnPropertyChanged("File");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private File _File;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Comment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Comments")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Comment : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="commentDate">Initial value of CommentDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Comment CreateComment(int ID, global::System.DateTime commentDate)
        {
            Comment comment = new Comment();
            comment.Id = ID;
            comment.CommentDate = commentDate;
            return comment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property CommentDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CommentDate
        {
            get
            {
                return this._CommentDate;
            }
            set
            {
                this.OnCommentDateChanging(value);
                this._CommentDate = value;
                this.OnCommentDateChanged();
                this.OnPropertyChanged("CommentDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CommentDate;
        partial void OnCommentDateChanging(global::System.DateTime value);
        partial void OnCommentDateChanged();
        /// <summary>
        /// There are no comments for Property CommentText in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CommentText
        {
            get
            {
                return this._CommentText;
            }
            set
            {
                this.OnCommentTextChanging(value);
                this._CommentText = value;
                this.OnCommentTextChanged();
                this.OnPropertyChanged("CommentText");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CommentText;
        partial void OnCommentTextChanging(string value);
        partial void OnCommentTextChanged();
        /// <summary>
        /// There are no comments for NoiseEmployee in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public NoiseEmployee NoiseEmployee
        {
            get
            {
                return this._NoiseEmployee;
            }
            set
            {
                this._NoiseEmployee = value;
                this.OnPropertyChanged("NoiseEmployee");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private NoiseEmployee _NoiseEmployee;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.LogEntry in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("LogEntries")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class LogEntry : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new LogEntry object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="entryDate">Initial value of EntryDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static LogEntry CreateLogEntry(int ID, global::System.DateTime entryDate)
        {
            LogEntry logEntry = new LogEntry();
            logEntry.Id = ID;
            logEntry.EntryDate = entryDate;
            return logEntry;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property EntryDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime EntryDate
        {
            get
            {
                return this._EntryDate;
            }
            set
            {
                this.OnEntryDateChanging(value);
                this._EntryDate = value;
                this.OnEntryDateChanged();
                this.OnPropertyChanged("EntryDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _EntryDate;
        partial void OnEntryDateChanging(global::System.DateTime value);
        partial void OnEntryDateChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property OldValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string OldValue
        {
            get
            {
                return this._OldValue;
            }
            set
            {
                this.OnOldValueChanging(value);
                this._OldValue = value;
                this.OnOldValueChanged();
                this.OnPropertyChanged("OldValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _OldValue;
        partial void OnOldValueChanging(string value);
        partial void OnOldValueChanged();
        /// <summary>
        /// There are no comments for Property NewValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NewValue
        {
            get
            {
                return this._NewValue;
            }
            set
            {
                this.OnNewValueChanging(value);
                this._NewValue = value;
                this.OnNewValueChanged();
                this.OnPropertyChanged("NewValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NewValue;
        partial void OnNewValueChanging(string value);
        partial void OnNewValueChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
